import type { ScenarioStep } from './AgentScenario';

// ── General-audience agentic scenarios ───────────────────────────────────────
// Non-security counterparts to the SOC scenarios in AIPlaygroundsView.
// Each one shows the same loop — reason, call a tool, read the result, revise —
// including the parts that matter most: a wrong turn the agent catches itself,
// and a stop where the agent hands the consequential decision back to a human.

// 1. Research that cannot be settled by a single search.
//    Carries the wrong-turn beat: the source that looked strongest is the wrong
//    population entirely, and the confident-sounding one is vendor marketing.
export const RESEARCH_ASSISTANT: ScenarioStep[] = [
  { type: 'think', label: 'Agent Reasons', content: 'Two approaches, one question — but "which is better" depends on what this team is optimising for and on how good the evidence actually is. One search will not settle it. Search broadly first, then judge the sources instead of trusting whatever ranked highest.' },
  { type: 'tool-call', label: 'Tool Call', content: 'search_sources(\n  query="daily stand-up meetings vs written async status updates, team coordination",\n  result_limit=6\n)' },
  { type: 'tool-result', label: 'Tool Result', content: '{\n  "results": [\n    { "id": "s1", "title": "The Async Advantage: Why Stand-ups Are Dead", "type": "whitepaper",   "claim": "async updates save teams ~8 hours per week" },\n    { "id": "s2", "title": "Synchronous check-ins and shared awareness",   "type": "peer_reviewed", "claim": "daily verbal check-ins improved coordination scores" },\n    { "id": "s3", "title": "Twelve teams that dropped stand-ups",           "type": "blog",          "claim": "mixed outcomes, methodology not stated" }\n  ],\n  "note": "s1 and s2 reach opposite conclusions"\n}' },
  { type: 'think', label: 'Agent Reasons', content: 's1 and s2 flatly contradict each other, and s1\'s headline number is exactly the kind of claim that needs provenance before I repeat it. Who published these, and what did they actually measure?' },
  { type: 'tool-call', label: 'Tool Call', content: 'get_source_metadata(\n  ids=["s1", "s2", "s3"]\n)' },
  { type: 'tool-result', label: 'Tool Result', content: '{\n  "s1": { "publisher": "vendor selling async status tooling", "peer_reviewed": false, "methodology": "not published", "sample": null },\n  "s2": { "publisher": "university research group",            "peer_reviewed": true,  "sample": "9 co-located assembly teams", "measured": "shift handover accuracy" },\n  "s3": { "publisher": "personal blog",                        "peer_reviewed": false, "sample": "self-selected, 12 teams" }\n}' },
  { type: 'think', label: 'Agent Reasons', content: 'I was about to lean on s2 as the serious counter-evidence — wrong turn. It is peer reviewed, but it studies co-located assembly teams handing over shifts, which is not a distributed knowledge-work team; the result does not transfer. And s1 is marketing for a product it is selling, with no methodology at all. Both are out. I need a narrower search aimed at the right population.' },
  { type: 'tool-call', label: 'Tool Call', content: 'search_sources(\n  query="written asynchronous updates, distributed knowledge-work teams, coordination and decision latency",\n  filters={ peer_reviewed: true, population: "distributed knowledge work" },\n  exclude_publisher_type="vendor"\n)' },
  { type: 'tool-result', label: 'Tool Result', content: '{\n  "results": [\n    { "id": "s4", "type": "peer_reviewed", "sample": "31 distributed software teams", "finding": "meeting time fell; decision latency rose where no decision owner was named" },\n    { "id": "s5", "type": "field_study",   "sample": "6 teams over 12 weeks",          "finding": "no delivery difference; 4 of 6 teams preferred async" }\n  ]\n}' },
  { type: 'think', label: 'Agent Reasons', content: 'A consistent picture is forming, and it is conditional rather than a verdict. The load-bearing claim is "meeting time drops without hurting coordination" — I should read the results section myself rather than trust a one-line summary of it.' },
  { type: 'tool-call', label: 'Tool Call', content: 'fetch_primary_source(\n  id="s4",\n  section="results"\n)' },
  { type: 'tool-result', label: 'Tool Result', content: '{\n  "effect":              "meeting time reduced",\n  "confidence_interval": "wide; overlaps zero for teams smaller than five",\n  "condition":           "benefit holds only where each update names a decision owner and a response deadline",\n  "limitation":          "self-reported time logs; no control for team tenure"\n}' },
  { type: 'think', label: 'Agent Reasons', content: 'That is enough to advise on, not enough to declare a winner. This also changes how everyone on the team works every day, so the decision belongs to the team, not to me. I will state what the evidence supports, the condition it depends on, and what I could not verify.' },
  { type: 'answer', label: 'Recommendation', content: '📚 Lean towards written async updates — with one condition attached. Moderate confidence, not settled.\n\nWhat the evidence supports:\n• Async written updates reduced meeting time across 31 distributed teams — but the effect overlaps zero for teams smaller than five\n• The gain held only where each update named a decision owner and a response deadline; without that, decisions took longer than under stand-ups\n• A 12-week field study found no delivery difference either way — preference decided it for most teams\n\nWhat I discarded, and why:\n• "Saves ~8 hours per week" came from a vendor selling async tooling, with no published methodology — not usable\n• The strongest-looking peer-reviewed source measured shift handovers on co-located assembly teams. Different population; it does not transfer, and I nearly weighted it heavily\n\nRemaining uncertainty: effect sizes rest on self-reported time logs, the intervals are wide, and nothing I found studies a team of your size and tenure directly.\n\nSuggested next step: run one cycle of async updates with a named decision owner per update, keep a single short weekly sync, and compare your own decision latency before and after. This is a team-wide working change — I have stopped at the recommendation; the adoption call is yours.' },
];

// 2. Planning inside hard constraints, ending at a human approval gate.
//    The first itinerary breaks the budget; the agent backs out, re-searches,
//    and then refuses to spend money without confirmation.
export const TRIP_PLANNER: ScenarioStep[] = [
  { type: 'think', label: 'Agent Reasons', content: 'Three constraints: the summit dates, a £900 ceiling covering flights and stay together, and a preference for flying direct. The cheapest itinerary is worthless if it lands on something already in the diary — calendar first, options second.' },
  { type: 'tool-call', label: 'Tool Call', content: 'get_calendar_availability(\n  person="traveller",\n  window="summit_week",\n  include=["confirmed", "tentative"]\n)' },
  { type: 'tool-result', label: 'Tool Result', content: '{\n  "Mon": "free",\n  "Tue": "free",\n  "Wed": "free",\n  "Thu": { "event": "Quarterly review", "status": "confirmed", "movable": false, "start": "09:00" },\n  "Fri": "free",\n  "note": "summit runs Mon-Wed"\n}' },
  { type: 'think', label: 'Agent Reasons', content: 'Summit runs Monday to Wednesday and Thursday\'s review cannot move, so the return has to land Wednesday evening. That rules out cheap Thursday-morning returns before I even look at prices.' },
  { type: 'tool-call', label: 'Tool Call', content: 'search_flights(\n  origin="home_city",\n  destination="summit_city",\n  depart="Mon",\n  return_by="Wed 22:00",\n  max_stops=1,\n  currency="GBP"\n)' },
  { type: 'tool-result', label: 'Tool Result', content: '[\n  { "code": "FL-114", "stops": 0, "depart": "Mon 07:40", "return": "Wed 18:20", "price": 392, "fare": "non-refundable" },\n  { "code": "FL-207", "stops": 1, "depart": "Mon 06:15", "return": "Wed 21:55", "price": 268, "arrives": "Mon 01:40 next day" },\n  { "code": "FL-451", "stops": 0, "depart": "Mon 16:05", "return": "Wed 19:40", "price": 428, "note": "misses summit opening session" }\n]' },
  { type: 'think', label: 'Agent Reasons', content: 'FL-207 is £124 cheaper but connects and lands after midnight — that is the preference I was asked to respect, and it costs a summit morning. FL-451 arrives too late to be useful. Taking FL-114 direct at £392, which leaves £508 for the stay.' },
  { type: 'tool-call', label: 'Tool Call', content: 'search_stays(\n  city="summit_city",\n  nights=3,\n  near="summit venue",\n  max_walk_minutes=10,\n  max_total=508,\n  currency="GBP"\n)' },
  { type: 'tool-result', label: 'Tool Result', content: '{\n  "matches": [],\n  "cheapest_in_radius": { "name": "Riverside Court", "per_night": 214, "total": 642, "walk_minutes": 6 },\n  "note": "venue district rates raised for summit week"\n}' },
  { type: 'think', label: 'Agent Reasons', content: 'The first plan breaks the budget by £134 — the venue district is priced for summit week. Rather than downgrade to the connecting flight and lose the stated preference, I will widen the radius and trade walking distance for a short, direct transit hop.' },
  { type: 'tool-call', label: 'Tool Call', content: 'search_stays(\n  city="summit_city",\n  nights=3,\n  max_transit_minutes=20,\n  transit_modes=["metro", "tram"],\n  max_total=480,\n  min_rating=4.2\n)' },
  { type: 'tool-result', label: 'Tool Result', content: '{\n  "matches": [\n    {\n      "name":             "Casa Alvorada (guesthouse)",\n      "per_night":        121,\n      "total":            363,\n      "transit_to_venue": "14 min metro, direct line",\n      "rating":           4.5,\n      "cancellation":     "free until 48h before check-in"\n    }\n  ],\n  "budget_remaining": 145\n}' },
  { type: 'think', label: 'Agent Reasons', content: '£755 all in, direct flight preserved, no clash with the review, £145 spare. Everything checks out — and this is exactly where I stop. Ticketing charges the card and the fare is non-refundable, so the last step is a human decision, not mine.' },
  { type: 'answer', label: 'Awaiting Approval', content: '🧳 Itinerary ready — nothing booked, nothing paid. Your confirmation needed.\n\nProposed trip (£755 of the £900 ceiling):\n• Flights — FL-114 direct, out Mon 07:40, back Wed 18:20 · £392 · non-refundable once ticketed\n• Stay — Casa Alvorada guesthouse, 3 nights · £363 · free cancellation until 48h before check-in\n• 14 min direct metro to the venue · £145 left for transfers and incidentals\n\nWhat I rejected and why:\n• FL-207 at £268 — one connection, lands at 01:40, and you asked to fly direct\n• Riverside Court beside the venue — £642 for three nights would have put the trip £134 over budget\n\nCalendar checked: summit Mon–Wed, and the Wednesday evening return keeps Thursday\'s quarterly review intact.\n\nReply "book it" and I will ticket the flight and confirm the guesthouse. I have not entered payment details or held the fare — the price can move until it is ticketed, so if the total shifts by more than £25 I will come back to you before paying.' },
];

// 3. Debugging a post-deploy error spike for the builder audience.
//    First hypothesis is contradicted by the metrics; the agent pivots,
//    finds the real cause, and leaves the deploy decision to a human.
export const BUG_INVESTIGATION: ScenarioStep[] = [
  { type: 'think', label: 'Agent Reasons', content: 'Error rate up twentyfold right after a release — the release is the obvious suspect, but obvious is not confirmed. Pull the actual errors first: the shape of the failure narrows this faster than guessing at causes.' },
  { type: 'tool-call', label: 'Tool Call', content: 'get_error_logs(\n  service="checkout-api",\n  window="since_deploy",\n  group_by="error_type",\n  limit=5\n)' },
  { type: 'tool-result', label: 'Tool Result', content: '{\n  "total_errors": 4182,\n  "groups": [\n    { "type": "PoolCheckoutTimeout", "count": 3961, "message": "timed out waiting for a connection from the pool" },\n    { "type": "SerializationError",  "count": 154,  "message": "unknown field in response body" },\n    { "type": "ValidationError",     "count": 67,   "message": "missing required field" }\n  ],\n  "first_error": "18 minutes after rollout completed"\n}' },
  { type: 'think', label: 'Agent Reasons', content: '95% are connection-pool timeouts, not the request-parsing failures I would have blamed. The 18-minute gap matters too — broken code fails on the first request, not eighteen minutes in. Working hypothesis: the release changed the query pattern and queries now hold connections longer.' },
  { type: 'tool-call', label: 'Tool Call', content: 'get_metrics(\n  service="checkout-api",\n  metrics=["db_query_p95_ms", "db_connections_in_use", "requests_per_second"],\n  window="deploy-30m..now"\n)' },
  { type: 'tool-result', label: 'Tool Result', content: '{\n  "db_query_p95_ms":       { "before": 42,      "after": 44,   "verdict": "flat" },\n  "db_connections_in_use": { "before": "18/50", "after": "50/50 since deploy+18m" },\n  "requests_per_second":   { "before": 62,      "after": 60,   "verdict": "flat" }\n}' },
  { type: 'think', label: 'Agent Reasons', content: 'Hypothesis is wrong — queries are as fast as they ever were and traffic has not moved, yet the pool is pinned at its ceiling. So connections are being taken and never handed back. Two candidates: a stalling dependency holding requests open, or our own code leaking. Rule out the dependency before I accuse the diff.' },
  { type: 'tool-call', label: 'Tool Call', content: 'get_upstream_health(\n  dependency="payment-status",\n  window="deploy-30m..now"\n)' },
  { type: 'tool-result', label: 'Tool Result', content: '{\n  "error_rate":     { "before": "0.05%", "after": "0.05%" },\n  "timeout_rate":   "~2 requests per minute, unchanged across the deploy",\n  "p95_latency_ms": { "before": 180, "after": 178 },\n  "verdict":        "dependency behaviour unchanged"\n}' },
  { type: 'think', label: 'Agent Reasons', content: 'The dependency is behaving exactly as it did before, so the change is ours. A slow leak at roughly the rate of those upstream timeouts would drain the pool in about the time we observed. Read what the release actually changed instead of theorising further.' },
  { type: 'tool-call', label: 'Tool Call', content: 'get_release_diff(\n  service="checkout-api",\n  release="current",\n  paths=["src/db/", "src/api/", "config/"]\n)' },
  { type: 'tool-result', label: 'Tool Result', content: '{\n  "files_changed": [\n    { "path": "src/db/session",     "summary": "retry wrapper added around get_payment_status; connection acquired outside the retry loop, released on the success path only" },\n    { "path": "config/runtime",     "summary": "retry.max_attempts 1 -> 4, retry.backoff_ms 0 -> 500" },\n    { "path": "src/api/serializers","summary": "response field renamed, no consumer update" }\n  ]\n}' },
  { type: 'think', label: 'Agent Reasons', content: 'That explains the delay precisely: the connection is checked out before the retry loop and only released when a call finally succeeds, so every request that exhausts all four attempts leaks one. About 2 upstream timeouts a minute against 32 free connections is roughly 18 minutes to saturation — which is exactly when the errors started. The serializer rename is a separate, smaller bug. The fix is small, but rollback versus forward-fix affects live checkout traffic, so that call is not mine to make.' },
  { type: 'answer', label: 'Diagnosis', content: '🐛 Root cause found: connection leak on the new retry path.\n\nWhat is happening:\n• The release wrapped the payment-status read in a retry loop but acquires the pool connection outside that loop and releases it only when a call succeeds\n• Every request that exhausts all four attempts leaks one connection permanently\n• At the steady ~2 upstream timeouts per minute, the 32 free connections drain in ~18 minutes — matching the observed onset exactly\n• Once the pool saturates, every request fails with PoolCheckoutTimeout, which is 95% of the 4,182 errors\n\nRuled out along the way: slower queries (p95 flat at ~44ms), a traffic surge (rps flat), and the payment-status dependency itself (error rate, timeouts and latency all unchanged).\n\nProposed fix:\n1. Acquire and release the connection inside each retry attempt, so every path returns it — scoped release rather than success-only\n2. Add a pool-checkout timeout alarm and a leaked-connection gauge, so this surfaces in seconds rather than after saturation\n3. Separately: the renamed response field is causing the 154 SerializationErrors — revert the rename or ship the consumer update alongside it\n\nRegression test to add: force N upstream timeouts against a small pool, then assert connections-in-use returns to baseline — the current suite never exercises the exhausted-retry path.\n\nOver to you: I have not touched the deploy. Rolling back restores service in minutes and takes the serializer bug with it; the forward fix is a few lines but ships under load. Your call which.' },
];
