#!/usr/bin/env bash
#
# aibloom container entrypoint — generated by the migrate-to-atlas skill.
#
# Everything here is RE-APPLIED ON EVERY START. That is the point: state lives
# on the bind mount, in a named volume, or is recreated here. Anything
# configured by hand inside a running container belongs in this file instead,
# or the next rebuild eats it.
#
set -uo pipefail

# --- git identity -------------------------------------------------------------
# ~/.gitconfig is NOT a named volume, so an image rebuild drops it and every
# commit then fails with "Author identity unknown". Declaring identity in
# compose and re-applying it here makes it reproducible infrastructure.
if [ -n "${GIT_USER_NAME:-}" ]; then
  git config --global user.name  "$GIT_USER_NAME"
  git config --global user.email "${GIT_USER_EMAIL:-}"
fi
git config --global init.defaultBranch main
git config --global --add safe.directory '*'

# Credential store on its own volume, isolated from the workspace so the token
# cannot leak into a repo, a build context, or a backup snapshot.
if [ -d /home/dev/.git-secrets ]; then
  git config --global credential.helper "store --file=/home/dev/.git-secrets/credentials"
fi

# --- the app ------------------------------------------------------------------
# Started in a DETACHED tmux session rather than as PID 1. A crash costs you
# the app, and `tmux attach -t app` shows you why.
#
# ⚠ Bind 0.0.0.0 HERE, in the launch command — never by editing the app's
# source. Safe only because compose publishes to 127.0.0.1 on the HOST.
if [ "${START_APP:-0}" = "1" ] && [ -n "${APP_CMD:-cd website && npm run dev -- --host 0.0.0.0 --port 5005}" ]; then
  if ! tmux has-session -t app 2>/dev/null; then
    tmux new-session -d -s app "cd /workspace && ${APP_CMD:-cd website && npm run dev -- --host 0.0.0.0 --port 5005}" \
      && echo "[entrypoint] app started in tmux session 'app' on :5005"
  fi
fi

exec "$@"
