import type { CourseModule } from '../../types/course';

const evM3: CourseModule = {
  id: 'ev-m3',
  title: 'Benchmarks, Regression, and Production',
  icon: 'zap',
  summary: 'What public benchmarks can and cannot tell you, contamination, regression suites that survive model upgrades, CI for prompts and agents, testing around non-determinism, and closing the loop from production traces back into the eval set.',
  lessons: [
    {
      id: 'ev3l1',
      diagram: 'BenchmarkHonesty',
      title: 'Reading Public Benchmarks Honestly',
      sectionLabel: 'Measurement',
      slides: [
        {
          heading: 'What They Are Good For',
          body: 'Public benchmarks are not worthless — they are just weaker evidence than their presentation implies. Used correctly they do three useful jobs. They track capability trends over time, which is how you know whether a class of problem has become tractable at all. They provide a coarse shortlist: a model far behind on reasoning-heavy suites is unlikely to surprise you on your reasoning-heavy task. And they give the field a shared vocabulary for discussing capability, without which every conversation restarts from scratch. What they cannot do is predict performance on your workload, because your workload has its own distribution, its own definition of correct, and a prompt and tool stack that no benchmark harness includes. Shortlist with public scores; decide with private ones.',
          bullets: [
            'Good for capability trends, coarse shortlisting, and shared vocabulary',
            'Bad at predicting performance on any specific production workload',
            'Small leaderboard gaps near the top rarely transfer to your tasks',
            'Shortlist publicly, decide privately — never the reverse',
          ],
        },
        {
          heading: 'Contamination',
          body: 'Benchmarks are published, models train on published text, so a high score may reflect memorisation rather than capability. This is structural rather than accidental, and it is hard to rule out: contamination can arrive through direct inclusion, through the countless derivative discussions, solutions, and tutorials that surround any popular benchmark, or through synthetic data generated by a model that had itself seen the test. The observable symptom is a gap between performance on a benchmark and performance on freshly constructed problems of the same type and difficulty. Defences exist and each is partial — canary strings that dataset authors ask trainers to filter, private held-out splits scored by the maintainer, and continuously refreshed benchmarks built from material published after training cutoffs. Treat any single reported score as an upper bound.',
          bullets: [
            'Contamination arrives indirectly too — via solutions, discussion, and synthetic derivatives',
            'The tell is a gap between benchmark scores and fresh problems of matched difficulty',
            'Private held-out splits and continuously refreshed sets are partial defences',
            'Read reported scores as upper bounds, especially on older, popular suites',
          ],
        },
        {
          heading: 'Saturation, Construct Validity, and Arenas',
          body: 'Two further problems limit what a benchmark number can mean. Saturation: once the frontier clusters near the ceiling, remaining headroom is dominated by label noise and ambiguous items, so ranking differences at the top measure error more than capability. Construct validity: a benchmark measures a specific operationalisation of a skill, and multiple-choice knowledge questions or self-contained coding problems are structurally unlike open-ended work in a real environment with ambiguous requirements and messy context. Human-preference arenas fix some of this by using real prompts and real comparisons, but they measure what raters prefer — which rewards style, length, and formatting alongside correctness — and their voter population is not your user population. Every benchmark is a proxy; know which proxy you are reading.',
          bullets: [
            'Near the ceiling, ranking deltas mostly reflect label noise',
            'Exam-shaped tasks are not product-shaped tasks — beware construct validity',
            'Preference arenas measure preference, including style and length effects',
            'Agentic benchmarks depend heavily on scaffold and environment, so scores travel poorly',
          ],
        },
      ],
    },
    {
      id: 'ev3l2',
      diagram: 'RegressionSuite',
      title: 'Regression Suites That Survive Model Upgrades',
      slides: [
        {
          heading: 'Assert on Outcomes, Not Phrasing',
          body: 'A regression suite earns its keep by staying valid across model changes, and the single biggest threat to that is assertions coupled to surface form. Exact-match checks against a reference paragraph, expected orderings of list items, specific phrasings in an explanation — all of these fail on a new model that is behaving perfectly well, generating a flood of false regressions precisely when you need to read a diff carefully. The discipline is to assert the properties that define correctness and nothing more: the required facts appear, the schema validates, the computed figure matches, the file compiles, the correct tool was called with valid arguments, the forbidden action never occurred. Write graders as though the wording will change on every run, because eventually it will.',
          bullets: [
            'Assert required content, structure, and post-conditions — never exact prose',
            'Surface-coupled assertions produce false regressions exactly when clarity matters most',
            'Prefer post-conditions on the world over inspection of the text describing them',
          ],
        },
        {
          heading: 'Separate the Contract from the Tuning',
          body: 'Prompts accumulate model-specific tuning — phrasings that worked around one family\'s quirks, formatting tricks, few-shot examples chosen for a particular tokenizer\'s habits. This is legitimate engineering that also becomes migration debt, because it is indistinguishable from essential behaviour once it is all one blob of text. Structure the prompt so the two are visibly separate: the contract — task definition, required output schema, hard constraints, domain rules — kept apart from the model-specific layer of phrasing and examples. Your suite should test the contract. When you evaluate a new model, you then re-tune the model-specific layer and hold the contract fixed, which turns a rewrite into a swap and makes it obvious whether a failure is a genuine capability gap or an artefact of tuning aimed at a different model.',
          bullets: [
            'Keep task contract and model-specific tuning in separate, composable pieces',
            'Evals target the contract; the tuning layer is expected to change per model',
            'A failure in the contract is a capability gap; a failure in tuning is a config task',
            'Run the suite against at least two model families to keep hidden coupling visible',
          ],
        },
        {
          heading: 'The Upgrade Drill',
          body: 'Treat model migration as a rehearsed procedure rather than an emergency. Run the full suite against the candidate model and read results by slice, not in aggregate. Expect a mix: genuine improvements, genuine regressions, and false regressions from cases that were always fragile — and investigate a sample of each rather than assuming. Where the new model behaves differently but arguably better, the case may be wrong; the correct response is to fix the case, and to note that a case whose expected answer changes because a better model appeared was probably over-specified. Then shadow the candidate on live traffic without serving its output, compare on production inputs, and roll out progressively with the eval suite running against real traffic. Do this on a schedule, not only when a deprecation notice forces it.',
          bullets: [
            'Read migration results by slice; aggregates hide the trade you are actually making',
            'Investigate regressions and improvements alike — some regressions are bad cases',
            'Shadow-run on live traffic before serving, then roll out progressively',
            'Rehearse upgrades on a cadence so the forced one is routine',
          ],
        },
        {
          heading: 'Keep the Suite from Rotting',
          body: 'Regression suites decay in predictable ways. They accumulate cases nobody understands, written for a bug fixed two rewrites ago, that now fail for reasons unrelated to their original purpose. They fill with near-duplicates from repeated incidents. They grow slow enough that people stop running them before merging. Counter all three deliberately: every case carries a one-line note on why it exists and what it protects, cases that have not failed in a long time get reviewed for whether they still discriminate, duplicates are merged, and the suite is split into a fast pre-merge tier and a comprehensive nightly tier. A regression suite is a code asset with maintenance costs, and the teams that treat it as write-once end up with a slow suite full of noise that everyone has learned to ignore.',
          bullets: [
            'Every case documents what it protects — undocumented cases become unremovable',
            'Review long-passing cases for continued relevance; merge duplicates',
            'Split fast pre-merge and comprehensive nightly tiers to protect iteration speed',
          ],
        },
      ],
    },
    {
      id: 'ev3l3',
      diagram: 'CIForPromptsAndAgents',
      title: 'CI for Prompts and Agents',
      slides: [
        {
          heading: 'Prompts Are Code',
          body: 'The behaviour of an AI system is determined as much by its prompts, tool descriptions, and rubrics as by its code, yet these artefacts routinely live outside every engineering control — edited in a console, stored in a database row, changed without review. Bring them in. Prompts belong in version control with meaningful diffs, code review by someone other than the author, and a deployment path that is auditable and revertible. Tool descriptions deserve particular attention because they are model-facing instructions that shape behaviour strongly and are usually written once and never reviewed. The test is simple and worth applying honestly: can you answer, for any output your system produced last Tuesday, exactly which prompt, tool schema, model, and rubric version were in play? If not, your evals cannot be reproduced and your incidents cannot be investigated.',
          bullets: [
            'Version prompts, tool schemas, rubrics, and grader code together with application code',
            'Review prompt diffs like code diffs; small edits have non-local behavioural effects',
            'Console-edited prompts break reproducibility and post-incident analysis',
          ],
        },
        {
          heading: 'Two Tiers and a Budget',
          body: 'Eval runs cost money and time, which makes tiering a design requirement rather than an optimisation. The pre-merge tier is a small, fast, mostly deterministic subset — a few minutes, single runs per case, focused on catching gross breakage and the specific regressions this change might plausibly cause. The nightly or pre-release tier is the full suite: every case, multiple runs each, judges included, results tracked as a trend. Put an explicit cost ceiling on CI evaluation and monitor it, because judge calls multiplied by cases multiplied by runs multiplied by pull requests grows faster than anyone expects. Cache aggressively where inputs and versions are unchanged, and make the cost of a full run visible so the trade-off between coverage and spend is a decision rather than an accident.',
          bullets: [
            'Fast deterministic subset pre-merge; full statistical suite nightly',
            'Cases times runs times judges times PRs — model the cost before it surprises you',
            'Cache results keyed on input, prompt, and model version',
            'Make eval spend a visible line item so coverage decisions are deliberate',
          ],
        },
        {
          heading: 'Hermetic Environments for Agent Evals',
          body: 'Agent evals are integration tests against a world, so the world has to be controlled or the results mean nothing. Every run needs a known starting state and full reset afterwards, because state leaking between runs produces failures that depend on execution order — the hardest class of eval bug to diagnose. Decide deliberately between mocked and live dependencies: mocks are fast, deterministic, and free, but they encode your assumptions about how the external system behaves, and agents fail in production precisely where those assumptions are wrong. Recorded interactions replayed back are a strong middle path. Keep a small live-integration tier that runs less often against real systems in a sandbox account, because the divergence between your mocks and reality is itself a failure mode worth measuring.',
          bullets: [
            'Known initial state and guaranteed teardown, or your results depend on run order',
            'Mocks encode assumptions; record-and-replay keeps realism without flakiness',
            'Keep a smaller live tier against sandboxed real systems to catch mock drift',
            'Never point agent evals at production systems or real customer accounts',
          ],
        },
        {
          heading: 'Gating Policy',
          body: 'Deciding what blocks a merge is a policy question that deserves an explicit answer rather than a default. Hard gates belong on things that are unambiguous and consequential: safety criteria, schema validity, a floor on the critical slice, and any case protecting a past incident. Soft signals — a small aggregate movement, a judge score wobble within its noise band — should be reported in the pull request without blocking, because gates that fire on noise are disabled within a month and then nothing is gated at all. Post the diff where the reviewer already is: which cases flipped in each direction, with links to the traces, so a human can judge whether a regression is acceptable. And write down who can override a gate and what they must record when they do.',
          bullets: [
            'Hard gate: safety, schema validity, critical-slice floors, incident regression cases',
            'Report-only: aggregate wobble inside the noise band — gating on noise kills the gate',
            'Post flipped cases with trace links in the PR; make the diff readable',
            'Define the override path explicitly, including what gets recorded',
          ],
        },
      ],
    },
    {
      id: 'ev3l4',
      diagram: 'NonDeterminismTesting',
      title: 'Testing Around Non-Determinism',
      slides: [
        {
          heading: 'Where the Variance Comes From',
          body: 'Non-determinism in these systems has several independent sources, and knowing which one you are facing determines what to do about it. Sampling is the obvious one and the only one you control directly. Below it sits numerical non-determinism: floating-point reduction order varies with batching and kernel selection on GPUs, so even greedy decoding is not bitwise reproducible across a shared serving fleet, and providers generally do not guarantee otherwise. Then there is the environment — tools returning different data, timestamps, other users\' concurrent activity, network flakiness. Finally, the provider itself: hosted models are updated, and behaviour can shift under a stable name. Temperature zero reduces variance substantially and does not eliminate it, which is why statistical treatment is the baseline rather than a fallback.',
          bullets: [
            'Sampling, floating-point batching effects, environment state, and provider-side change',
            'Greedy decoding is not a determinism guarantee on shared infrastructure',
            'Pin model versions where the platform allows and record them with every result',
            'Design for variance rather than trying to engineer it away',
          ],
        },
        {
          heading: 'Runs, Rates, and Where to Spend',
          body: 'Handle variance by running each scenario several times and asserting on the rate. Two framings are useful and answer different questions: the probability that a single attempt succeeds, and the probability that all of k attempts succeed — the latter matters when a user only sees one attempt and any failure is visible. For unattended automation, consistency across runs is often more important than peak capability, and reporting the worst observed run alongside the mean captures that. Given a fixed budget, the usual trade favours more cases over more runs per case, since case diversity samples the input distribution while extra runs only refine the estimate for inputs you already have — with the exception of scenarios you already know are borderline, where extra runs are exactly what resolves them.',
          bullets: [
            'Report pass rate, not a single transcript; a lucky run is not evidence',
            'Consistency across runs matters more than peak for unattended automation',
            'Budget usually buys more from additional cases than additional runs',
            'Spend extra runs on scenarios already known to be marginal',
          ],
        },
        {
          heading: 'Flaky Case or Degraded System',
          body: 'When a case starts failing intermittently you have to distinguish three explanations, and they call for opposite responses. The system genuinely regressed and the pass rate dropped — investigate and fix. The case was always marginal, sitting near the system\'s capability boundary, and normal variance is now visible — record its true rate and treat movement as signal. Or the case or environment is broken: ambiguous expectations, state leaking between runs, an unreliable external dependency. Historical pass rates settle this immediately, which is the argument for storing every run rather than only the latest verdict. A case whose rate has been stable at seventy percent for months and is stable at seventy percent today has not regressed, however uncomfortable the red mark in the report looks.',
          bullets: [
            'Store every run so historical rates are available at triage time',
            'Marginal cases live near the capability boundary — they are informative, not broken',
            'Order-dependent failures point at environment state, not the model',
            'Quarantine genuinely broken cases; never delete a case that merely fails often',
          ],
        },
      ],
    },
    {
      id: 'ev3l5',
      diagram: 'ObservabilityLoop',
      title: 'Observability and Closing the Loop',
      slides: [
        {
          heading: 'Traces Are the Substrate',
          body: 'Offline evals tell you how the system performs on cases you have collected; production tells you what is actually happening, and the connection between them is tracing. An agent run is a tree — run, steps, model calls, tool calls, subagent spans — and the trace must capture the prompt as assembled after templating, truncation, and context management rather than the template you believe you sent, because the gap between those two is where a large share of production bugs live. Attach tokens, latency, and cost to every span, along with the identifiers needed to slice later. Whether you use OpenTelemetry\'s GenAI conventions or an LLM-native tracing platform matters far less than picking one before launch, because retrofitting tracing during an incident is a uniquely bad experience.',
          bullets: [
            'Trace the tree: run, steps, model and tool calls, nested subagent spans',
            'Capture the assembled prompt and raw tool results — reconstructions mislead',
            'Attach cost, tokens, and latency per span, not just per run',
            'Choose the tracing approach before launch; retrofitting during an incident is painful',
          ],
        },
        {
          heading: 'Online Signals and Guardrail Evals',
          body: 'Production carries quality signals if you instrument for them. Implicit ones are the most abundant and the most honest: retries, rephrasings of the same question, conversation abandonment, escalation to a human, users copying only part of an answer, edits made to generated content before it is used. Explicit feedback is sparse and biased toward extremes, useful mainly as a pointer to traces worth reading. On top of these, run lightweight automated checks over live traffic — schema validity, groundedness against retrieved sources, refusal rate, policy checks — sampled at a rate you can afford, giving a continuous quality signal between offline runs. Alert on movement in those signals rather than only on errors, because the characteristic production failure here is a quality slide with a perfectly healthy error rate.',
          bullets: [
            'Implicit signals — retry, rephrase, abandon, escalate, edit — outnumber and outperform thumbs',
            'Sampled online checks give continuous quality signal between offline runs',
            'Alert on quality drift, not just errors; degradation is silent by default',
            'Segment online metrics the same way you slice offline evals',
          ],
        },
        {
          heading: 'The Loop That Closes',
          body: 'The point of production observability is not the dashboard, it is the pipeline from failure to permanent test. Make it a defined workflow with an owner: someone reviews flagged and sampled traces on a fixed cadence, classifies each failure by mode, and converts the informative ones into eval cases with expected outcomes and graders. New cases enter the dev set, get confirmed as currently failing, and stay in the suite forever after the fix. Two habits keep this alive. First, define a target for how quickly a production failure becomes a case — an incident that has not produced a regression test within the week usually never will. Second, track the failure-mode distribution over time, because the shape of that histogram is what tells you whether the last quarter of work actually moved anything.',
          bullets: [
            'Named owner and fixed cadence for trace review — otherwise it does not happen',
            'Every incident becomes a permanent case; the suite is institutional memory',
            'Set a time target from production failure to eval case',
            'Track the failure-mode distribution over time as the real progress metric',
          ],
        },
        {
          heading: 'Guarding the Gap Between Offline and Online',
          body: 'Offline scores and production quality drift apart, and the divergence is itself a metric worth watching. Common causes: the input distribution has moved and the eval set no longer looks like traffic, the eval environment has diverged from production configuration, or the suite has been tuned against until it flatters the system. Check the relationship deliberately — sample recent production traces, grade them with the same rubrics you use offline, and compare against what the suite predicts. A persistent gap means the suite has stopped being representative and needs refreshing from current traffic rather than defending. This check is cheap, most teams never run it, and it is the difference between a suite that reflects the product and a suite that reflects the product as it was when someone last cared.',
          bullets: [
            'Grade sampled production traffic with the offline rubrics and compare',
            'A persistent offline-online gap means the case mix has gone stale',
            'Verify the eval environment matches production configuration, not an idealised version',
            'Refresh from current traffic on a schedule, not when someone complains',
          ],
        },
      ],
      roleContent: [
        {
          role: 'general',
          label: 'General User',
          body: 'Good AI teams watch how their system behaves in the wild and feed every real failure back into their tests. If a product you report a problem with never seems to fix that class of issue, that loop is missing.',
          bullets: [
            'Ask vendors what happens to a reported failure after the immediate fix',
            'Quality can slide without any error message — someone has to be measuring',
            'Products that improve steadily have a feedback loop; products that only change do not',
          ],
        },
        {
          role: 'security-se',
          label: 'Security SE',
          body: 'Tracing is a security and audit capability as much as an engineering one. When something goes wrong with an agent, the trace is the only evidence of what it was told, what it decided, and what it touched — and the absence of one is a finding in its own right.',
          bullets: [
            'Ask to see a full trace of an agent run, including assembled prompts and tool arguments',
            'No replayable trace means no incident investigation and no forensic answer',
            'Quality drift alerting doubles as detection for prompt-injection campaigns and abuse',
            'Confirm traces containing sensitive content are access-controlled and retention-bounded',
          ],
        },
        {
          role: 'developer',
          label: 'Developer',
          body: 'Instrument tracing before launch and wire trace review into the sprint, or your eval set will slowly stop resembling what users do. The pipeline from production failure to permanent regression case should be a normal, boring workflow.',
          bullets: [
            'Log assembled prompts, tool calls with arguments, and results at span level',
            'Sample cheap online graders over live traffic for continuous quality signal',
            'One-click path from a production trace to a new eval case, or it will not happen',
            'Periodically grade production samples with offline rubrics to detect suite staleness',
          ],
        },
        {
          role: 'consultant',
          label: 'AI Consultant',
          body: 'Most clients buy observability tooling and never staff the review. The deliverable that matters is the operating rhythm: who reads traces, how often, what they do with what they find, and how quickly a production failure becomes a permanent test.',
          bullets: [
            'Define the trace-review cadence, owner, and escalation path in the operating model',
            'Set a target time from production failure to eval case and report against it',
            'Include tracing, retention, and access controls in the governance and privacy review',
            'Report failure-mode distribution shifts to sponsors — it is the clearest progress evidence',
          ],
        },
      ],
    },
    {
      id: 'ev3l6',
      diagram: 'CostLatencyFrontier',
      title: 'Cost and Latency as First-Class Metrics',
      slides: [
        {
          heading: 'Measure Per Task, Not Per Call',
          body: 'Per-call token pricing is the wrong unit for reasoning about an AI system, because users do not buy calls — they complete tasks. The meaningful figure is total cost to complete one real task successfully, including retries, failed attempts, judge calls in the loop, and every step of an agent trajectory. Agents amplify the difference dramatically: a loop re-sends its growing context on every iteration, so a task that looks cheap per call can be expensive per completion, and a cheaper model that needs more steps or more retries can cost more overall than the expensive one. Report cost per successful task alongside quality in every eval run, and the model-selection conversation stops being about list prices and starts being about economics.',
          bullets: [
            'Cost per successful task, including retries and failures — not cost per call',
            'Agent loops re-send context every step; per-call intuition breaks down',
            'A cheaper model that needs more steps is not cheaper',
            'Failed attempts are part of the cost of the successes',
          ],
        },
        {
          heading: 'Latency Is Distribution, Not Average',
          body: 'Mean latency describes an experience nobody has. Report the distribution, and pay attention to the tail, because in a multi-step agent the tail dominates: a run with a dozen sequential steps inherits the slow tail of each one, and the probability that at least one step is slow rises quickly with step count. Time to first token is a different metric from time to completion and matters more for perceived responsiveness in interactive products, while for background automation only completion time matters and the whole optimisation changes. Latency is also an architectural constraint rather than an afterthought — it is what pushes you toward parallel tool calls, streaming progress, smaller models for routine steps, and speculative work that is discarded if unneeded.',
          bullets: [
            'Report p50, p95, p99 — tail latency is what users remember',
            'Multi-step agents compound tail risk with every sequential step',
            'Time to first token and time to completion are different products of different designs',
            'Latency budgets drive architecture: parallelism, routing, streaming, smaller models',
          ],
        },
        {
          heading: 'The Quality-Cost Frontier',
          body: 'Quality, cost, and latency trade against each other, and pretending otherwise leads to systems that are excellent and unaffordable. Evaluate configurations as points on a frontier rather than ranking them on quality alone: for each candidate — model, prompt strategy, number of reasoning steps, retrieval depth, judge usage — plot quality against cost per successful task and pick knowingly. The results are frequently unintuitive, because quality often flattens well before cost does, and a configuration a couple of points behind the best may cost a fraction as much. Routing exploits this directly: send easy inputs to a small model, escalate hard ones, and evaluate the routed system end to end. But evaluate the whole system, because a router that misclassifies difficulty can be worse and pricier than either model alone.',
          bullets: [
            'Plot quality against cost per successful task; choose a point deliberately',
            'Quality usually flattens before cost does — the top configuration rarely wins on value',
            'Cascades and routing exploit the frontier; evaluate the routed system end to end',
            'Prompt-cache-friendly layout is a real cost lever in agent loops',
          ],
        },
        {
          heading: 'Regressions in Cost Are Regressions',
          body: 'Teams gate on quality and let cost and latency drift, which is how a system quietly becomes twice as expensive over two quarters with no single change to blame. Put cost and latency in the same report as quality, with the same tiering and the same alerting, and treat a significant increase as a regression requiring justification even when quality improved. The usual culprits are cumulative and individually reasonable: a longer system prompt, an extra retrieved chunk, one more judge call, a retry policy that got more generous, a cache-invalidating token added early in the prompt. Each is defensible alone and the aggregate is not. Reviewing the cost diff on every change is a five-minute habit that prevents an expensive, hard-to-unwind surprise.',
          bullets: [
            'Report cost and latency next to quality on every run, with the same gates',
            'Cost creep is cumulative and individually reasonable — review the diff per change',
            'Watch for cache-invalidating edits early in prompts; they multiply across agent steps',
            'A quality win that triples cost is a trade-off decision, not an automatic ship',
          ],
        },
      ],
    },
  ],
  quiz: [
    { q: 'What is the most defensible use of public benchmark scores?', options: ['Selecting the production model for a specific workload', 'Coarse shortlisting and tracking capability trends, with private evals making the decision', 'Setting acceptance criteria in a customer contract', 'Estimating cost per task at production volume'], correct: 1 },
    { q: 'Why does benchmark contamination inflate scores even when the test set was never directly included in training?', options: ['Because benchmarks are graded by model judges', 'Because larger models memorise more parameters by design', 'Because solutions, discussions, and synthetic derivatives of popular benchmarks pervade training corpora', 'Because contamination only affects multiple-choice formats'], correct: 2 },
    { q: 'Which assertion style makes a regression suite most likely to survive a model upgrade?', options: ['Exact string match against a stored reference answer', 'Checking that responses are within a fixed word count', 'Requiring identical ordering of list items', 'Asserting required facts, schema validity, and post-conditions on the world'], correct: 3 },
    { q: 'Why separate a prompt\'s task contract from its model-specific tuning?', options: ['So the suite tests durable behaviour while the tuning layer is re-fitted per model', 'To reduce the token count of the system prompt', 'Because providers require structured prompt sections', 'To allow the judge to grade each section separately'], correct: 0 },
    { q: 'What is the argument against hard-gating merges on small aggregate eval movements?', options: ['Aggregate scores cannot be computed reliably in CI', 'Gates that fire on statistical noise get disabled, after which nothing is gated', 'Aggregate movements are always caused by flaky infrastructure', 'Merge gates are incompatible with nightly suites'], correct: 1 },
    { q: 'Given a fixed eval budget, what generally yields more information?', options: ['More runs per existing case, since variance is the main problem', 'More cases, since case diversity samples the input distribution', 'A larger judge model applied to the same cases', 'Longer timeouts per run'], correct: 1 },
    { q: 'Your offline eval scores stay flat while production quality complaints rise. What is the most likely explanation?', options: ['The judge model needs a higher temperature', 'Production is running a different random seed', 'The eval set no longer represents current traffic, or has been tuned against', 'Tracing overhead is degrading responses'], correct: 2 },
    { q: 'Why is cost per successful task a better metric than cost per API call for agents?', options: ['Because providers bill agents differently from single calls', 'Because it includes retries, failed attempts, and every loop iteration that a per-call figure hides', 'Because per-call pricing changes too frequently to track', 'Because latency and cost are the same measurement'], correct: 1 },
  ],
};

export default evM3;
